Add if_any option to map field
balance-platform/talos pull request #11
Opened 2021-01-18 06:44 UTC by natali-maximenko

В структуру `Talos.Types.MapType.Field` добавлен ключ `if_any: boolean`

Ожидаемое поведение: 
если `if_any: true` то хотя бы один из ключей в мапе должен быть не пустой

2021-01-18 06:55 UTC, sofakingworld commented
Эта реализация кажется не решает наш рабочий случай, когда нужно проверить работу связки фио + др или ИНН

2021-01-18 06:59 UTC, natali-maximenko commented
Она и не пытается его решать, я начала с простого, когда один параметр обязательный.

2021-01-18 08:23 UTC, sofakingworld commented
Текущую проверку лучше реализовать в самом Talos.Types.MapType, как `has_any_key` или что-то типа того

2021-01-18 15:51 UTC, sofakingworld commented on test/types/map_type_test.exs
> +               "lastname" => "Минаев",
Выдуманный человек же?

2021-01-18 18:16 UTC, natali-maximenko commented on test/types/map_type_test.exs
> +               "lastname" => "Минаев",
уберу

2021-01-19 09:39 UTC, sofakingworld requested changes

2021-01-19 09:39 UTC, sofakingworld commented on lib/types/map_type.ex
> +      # проверить поля из required_groups
Интернациональный ресурс, комменты оставляем на английском

2021-01-19 09:39 UTC, sofakingworld commented on test/types/map_type_test.exs
> +               "lastname" => "Лорка",
Аналогично, давай на кривом английском писать :) 

В Pillar было бы меньше ПРов, если бы я по-русски писал

2021-01-19 09:39 UTC, sofakingworld commented on lib/types/map_type.ex
> +    cond do
По моему опыту: я допустил много ошибок с паттернатчингом функций, поэтому рекомендую все проверки делать в одной функции errors, а не разносить на несколько разных

В общем кмк лучше сюда в конд прокинуть прочие проверки (сами проверки для удобства можно раскидать по приватным функциям)

2021-01-19 09:39 UTC, sofakingworld commented on lib/types/map_type.ex
> +    required_groups: nil
Пока не совсем понял, как это работает. флага "опциональный" у полей недостаточно?

2021-01-19 09:39 UTC, sofakingworld commented on lib/types/map_type.ex
> +    `options`:
В документацию при добавлении новых опций нужно добавить описание/примеры использования

2021-01-19 13:23 UTC, natali-maximenko commented on lib/types/map_type.ex
> +    cond do
вынесла в одну функцию

2021-01-19 16:03 UTC, natali-maximenko commented on lib/types/map_type.ex
> +    required_groups: nil
расписала в описании PR'а. Опциональность даёт возможность не проверять поле, для случая, когда мне нужно любое из трёх полей, нужна динамическая опциональность. Есть одно, не хочу смотреть на два остальных.

2021-01-19 16:03 UTC, natali-maximenko commented on lib/types/map_type.ex
> +    `options`:
добавила

2021-01-20 07:10 UTC, natali-maximenko commented
@sofakingworld посмотри пожалуйста

2021-01-24 22:38 UTC, merged